---

#Old way of doing the go stuff. No longer works now that we are on 1.20 and above
# - name: Install go so that we can build things locally
#   apt:
#     pkg: 
#       - golang
#     state: latest

# - name: Fetch and build the client
#   command: go get -f -u github.com/baaahs/chat/bchat-tty

- name: Install our code
  command: /usr/local/go/bin/go install github.com/baaahs/chat/bchat-tty@latest

- name: Copy the tty template file
  copy:
    dest: /etc/systemd/system/getty@tty1.service
    remote_src: yes
    src: /lib/systemd/system/getty@.service

- name: Make it specific to tty1
  replace:
    path: /etc/systemd/system/getty@tty1.service
    regexp: '%I'
    replace: tty1

#- name: Install the bchat command
#  replace:
#    path: /etc/systemd/system/getty@tty1.service
#    regexp: '^ExecStart=(.+)$'
#    # The options here are
#    # -i don't show /etc/issue
#    # -n don't prompt for a login name
#    # -l use the specified command rather than /bin/login
#    # -o pass these arguments to the command. We're using these to know that it
#    #         is the tty instance that is running by setting an additional ACL string
#    #         that gets parsed into bchat's config
#    replace: 'ExecStart=-/sbin/agetty -i -n -l /root/go/bin/bchat-tty -o "tty=tty1" tty1 linux'


- name: Install the bchat command
  ini_file:
    path: /etc/systemd/system/getty@tty1.service
    no_extra_spaces: yes
    section: Service
    option: ExecStart
    # The options here are
    # -i don't show /etc/issue
    # -n don't prompt for a login name
    # -l use the specified command rather than /bin/login
    # -o pass these arguments to the command. We're using these to know that it
    #         is the tty instance that is running by setting an additional ACL string
    #         that gets parsed into bchat's config
    value: '-/sbin/agetty -i -n -l /root/go/bin/bchat-tty -o "tty=tty1" tty1 ansi'


- name: Let bchat restart forever without going into failure
  ini_file:
    path: /etc/systemd/system/getty@tty1.service
    section: Unit
    option: StartLimitIntervalSec
    value: "0"
    no_extra_spaces: yes

- name: Give it a config file
  template:
    src: bchat.acl.j2
    dest: /etc/bchat.acl


- name: Restart the tty1 service so it's using the new code & config
  systemd:
    daemon_reload: yes
    state: restarted
    name: getty@tty1.service