---

- name: Install go so that we can build things locally
  apt:
    pkg: 
      - golang
    state: latest

- name: Fetch and build the client
  command: go get -f -u github.com/baaahs/chat/bchat-tty

- name: Copy the tty template file
  copy:
    dest: /etc/systemd/system/getty@tty1.service
    remote_src: yes
    src: /lib/systemd/system/getty@.service

- name: Make it specific to tty1
  replace:
    path: /etc/systemd/system/getty@tty1.service
    regexp: '%I'
    replace: tty1

- name: Install the bchat command
  replace:
    path: /etc/systemd/system/getty@tty1.service
    regexp: '^ExecStart=(.+)$'
    # The options here are
    # -i don't show /etc/issue
    # -n don't prompt for a login name
    # -l use the specified command rather than /bin/login
    # -o pass these arguments to the command. We're using these to know that it
    #         is the tty instance that is running by setting an additional ACL string
    #         that gets parsed into bchat's config
    replace: 'ExecStart=-/sbin/agetty -i -n -l /root/go/bin/bchat-tty -o "tty=tty1" tty1 linux'

- name: Give it a config file
  template:
    src: bchat.acl.j2
    dest: /etc/bchat.acl

- name: Restart the tty1 service
  systemd:
    daemon_reload: yes
    state: restarted
    name: getty@tty1.service