---

- name: Install go so that we can build things locally
  apt:
    pkg: 
      - golang
    state: latest

- name: Fetch and build the client
  command: go get -f -u github.com/baaahs/chat/bchat-tty

- name: Copy the tty template file
  copy:
    dest: /etc/systemd/system/getty@tty1.service
    remote_src: yes
    src: /lib/systemd/system/getty@.service

- name: Make it specific to tty1
  replace:
    path: /etc/systemd/system/getty@tty1.service
    regexp: '%I'
    replace: tty1

- name: Install the bchat command
  replace:
    path: /etc/systemd/system/getty@tty1.service
    regexp: '^ExecStart=(.+)$'
    replace: 'ExecStart=-/sbin/agetty -i -n -l /root/go/bin/bchat-tty tty1 linux'

- name: Give it a config file
  template:
    src: bchat.acl.j2
    dest: /etc/bchat.acl

- name: Restart the tty1 service
  systemd:
    daemon_reload: yes
    state: restarted
    name: getty@tty1.service