---

- name: Install go so that we can build things locally
  apt:
    pkg: 
      - golang
    state: latest

- name: Fetch and build the client
  command: go get github.com/baaahs/chat/bchat-tty

- name: Copy the tty template file
  copy:
    dest: /etc/systemd/system/getty@tty1.service
    remote_src: yes
    src: /lib/systemd/system/getty@.service

- name: Make it specific to tty1
  replace:
    path: /etc/systemd/system/getty@tty1.service
    regexp: '%I'
    replace: tty1

- name: Install the bchat command
  replace:
    path: /etc/systemd/system/getty@tty1.service
    regexp: '^ExecStart=(.+)$'
    replace: 'ExecStart=-/sbin/agetty -i -n -l /home/baaahs/go/bin/bchat-tty tty1 linux'
